name: 'dbtproject'
version: '1.0.0'
config-version: 2

profile: 'dbtproject'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:        
  - "target"
  - "dbt_packages"

models:
  projectB:
    flatten:
      +materialized: view
      +group: mart_models
    
    #result:
    #  +group: analytics_models

    staging:
      +group: staging_models

